<?xml version="1.0" encoding="utf-8"?><Database Name="StrongerOrg" Class="DataClassesLocksmithDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=StrongerOrg;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="StrongerOrgConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Technician" Member="Technicians">
    <Type Name="Technician">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Company">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Zip Code]" Member="Zip_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Jobs" Member="Jobs">
    <Type Name="Job">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Technician" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Mobile Phone]" Member="Mobile_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Job Type]" Member="Job_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Job Pricing]" Member="Job_Pricing" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Total" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cost" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Payment Method]" Member="Payment_Method" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Gross" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Gross-Cost]" Member="Gross_Cost" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Tech Cut]" Member="Tech_Cut" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Tech Payout]" Member="Tech_Payout" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Company Payout]" Member="Company_Payout" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Net pay]" Member="Net_pay" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Sum Cash]" Member="Sum_Cash" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>