//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongerOrg.Backoffice.MiriMargolin {
    
    
    public partial class GuestBook {
        
        /// <summary>
        /// Feedbacks1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StrongerOrg.Backoffice.UserControls.Feedbacks Feedbacks1;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new StrongerOrg.Backoffice.BackOffice Master {
            get {
                return ((StrongerOrg.Backoffice.BackOffice)(base.Master));
            }
        }
    }
}
