//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongerOrg.Backoffice {
    
    
    public partial class BracketsDisplay {
        
        /// <summary>
        /// LinkButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton1;
        
        /// <summary>
        /// Bracket1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TourneyLogic.Web.UI.WebControls.Bracket Bracket1;
        
        /// <summary>
        /// BracketCompetitor3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TourneyLogic.Web.UI.WebControls.BracketCompetitor BracketCompetitor3;
        
        /// <summary>
        /// BracketCompetitor4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TourneyLogic.Web.UI.WebControls.BracketCompetitor BracketCompetitor4;
        
        /// <summary>
        /// BracketCompetitor5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TourneyLogic.Web.UI.WebControls.BracketCompetitor BracketCompetitor5;
        
        /// <summary>
        /// BracketCompetitor6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TourneyLogic.Web.UI.WebControls.BracketCompetitor BracketCompetitor6;
        
        /// <summary>
        /// BracketCompetitor7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TourneyLogic.Web.UI.WebControls.BracketCompetitor BracketCompetitor7;
        
        /// <summary>
        /// BracketCompetitor8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TourneyLogic.Web.UI.WebControls.BracketCompetitor BracketCompetitor8;
        
        /// <summary>
        /// BracketCompetitor9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TourneyLogic.Web.UI.WebControls.BracketCompetitor BracketCompetitor9;
        
        /// <summary>
        /// BracketCompetitor10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TourneyLogic.Web.UI.WebControls.BracketCompetitor BracketCompetitor10;
    }
}
